-- Database: StudentPathGuideDB_V2
-- User: apex
-- Password: 123

CREATE TABLE Course (
    Course_Id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    Course_name VARCHAR(255) NOT NULL,
    Course_field VARCHAR(255) NOT NULL,
    Course_min_aps INT NOT NULL,
    Course_description TEXT,
    Course_required_subjects VARCHAR(500)
);

CREATE TABLE University (
    University_id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    University_name VARCHAR(255) NOT NULL,
    University_abbreviation VARCHAR(50) NOT NULL,
    University_province VARCHAR(100) NOT NULL,
    University_website VARCHAR(255)
);

CREATE TABLE University_courses (
    Id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    University_id BIGINT NOT NULL,
    Course_id BIGINT NOT NULL,
    Faculty_name VARCHAR(255),
    Min_aps_override INT,
    CONSTRAINT fk_university FOREIGN KEY (University_id) REFERENCES University(University_id) ON DELETE CASCADE,
    CONSTRAINT fk_course FOREIGN KEY (Course_id) REFERENCES Course(Course_Id) ON DELETE CASCADE
);

INSERT INTO University (id, university_name, university_abbreviation, university_province, university_website) VALUES
(1, 'University of Cape Town', 'UCT', 'Western Cape', 'https://www.uct.ac.za'),
(2, 'University of Pretoria', 'UP', 'Gauteng', 'https://www.up.ac.za'),
(3, 'University of the Witwatersrand', 'WITS', 'Gauteng', 'https://www.wits.ac.za'),
(4, 'Stellenbosch University', 'SU', 'Western Cape', 'https://www.sun.ac.za'),
(5, 'University of KwaZulu-Natal', 'UKZN', 'KwaZulu-Natal', 'https://www.ukzn.ac.za');

INSERT INTO Course (id, course_name, course_field, course_min_aps, course_description, course_required_subjects) VALUES
(1, 'BCom Accounting Sciences', 'Commerce', 34, 'Accounting, auditing, taxation and financial management.', 'Mathematics, English'),
(2, 'BSc Computer Science', 'Engineering & IT', 28, 'Programming, algorithms, systems and software engineering.', 'Mathematics, Physical Science'),
(3, 'LLB Law', 'Law', 32, 'Legal studies, constitutional law and criminal law.', 'English, Mathematics'),
(4, 'MBChB Medicine', 'Health Sciences', 35, 'Medical training for doctors.', 'Mathematics, Physical Science, Life Sciences'),
(5, 'BScAgric Agricultural Economics', 'Agriculture', 30, 'Agricultural economics and agribusiness management.', 'Mathematics, Physical Science'),
(6, 'BCom Finance', 'Commerce', 32, 'Financial markets, investments, banking and corporate finance.', 'Mathematics, English'),
(7, 'BCom Economics', 'Commerce', 30, 'Microeconomics, macroeconomics and economic policy.', 'Mathematics, English'),
(8, 'BCom Information Systems', 'Engineering & IT', 28, 'Business information systems and IT strategy.', 'Mathematics, English'),
(9, 'BSc Mathematics', 'Science', 28, 'Pure and applied mathematics and statistics.', 'Mathematics, English'),
(10, 'BSc Physics', 'Science', 30, 'Classical mechanics, quantum physics and thermodynamics.', 'Mathematics, Physical Science'),
(11, 'BSc Chemistry', 'Science', 30, 'Organic, inorganic and physical chemistry.', 'Mathematics, Physical Science, Life Sciences'),
(12, 'BSc Electrical Engineering', 'Engineering & IT', 32, 'Electrical systems, circuits and power engineering.', 'Mathematics, Physical Science'),
(13, 'BSc Mechanical Engineering', 'Engineering & IT', 32, 'Mechanics, thermodynamics and design engineering.', 'Mathematics, Physical Science'),
(14, 'BSc Civil Engineering', 'Engineering & IT', 32, 'Structural engineering, construction and infrastructure.', 'Mathematics, Physical Science'),
(15, 'BSc Chemical Engineering', 'Engineering & IT', 34, 'Chemical processes, materials and industrial chemistry.', 'Mathematics, Physical Science, Life Sciences'),
(16, 'BSc Nursing', 'Health Sciences', 28, 'Patient care, clinical nursing and healthcare management.', 'Mathematics, Life Sciences, English'),
(17, 'BSc Pharmacy', 'Health Sciences', 34, 'Pharmacology, medicines and pharmaceutical sciences.', 'Mathematics, Physical Science, Life Sciences'),
(18, 'BSc Physiotherapy', 'Health Sciences', 32, 'Movement rehabilitation and physical therapy.', 'Mathematics, Life Sciences, English'),
(19, 'BSc Occupational Therapy', 'Health Sciences', 30, 'Helping people perform daily activities through therapy.', 'Mathematics, Life Sciences, English'),
(20, 'BA Psychology', 'Humanities', 26, 'Human behaviour, mental health and counselling.', 'English, Mathematics'),
(21, 'BA Social Work', 'Humanities', 24, 'Community development, social welfare and human rights.', 'English, Life Sciences'),
(22, 'BA Journalism', 'Humanities', 26, 'Media, reporting and digital journalism.', 'English, History'),
(23, 'BA Political Science', 'Humanities', 26, 'Government, politics and international relations.', 'English, History'),
(24, 'BA Education', 'Education', 24, 'Teaching methodology and educational psychology.', 'English, Mathematics'),
(25, 'BSc Architecture', 'Engineering & IT', 32, 'Building design, urban planning and architectural theory.', 'Mathematics, Physical Science'),
(26, 'BSc Quantity Surveying', 'Engineering & IT', 28, 'Construction costs and project budgeting.', 'Mathematics, English'),
(27, 'BCom Marketing', 'Commerce', 26, 'Consumer behaviour, branding and digital marketing.', 'Mathematics, English'),
(28, 'BCom Human Resource Management', 'Commerce', 26, 'People management and labour law.', 'English, Mathematics'),
(29, 'BCom Supply Chain Management', 'Commerce', 26, 'Logistics, procurement and supply chain operations.', 'Mathematics, English'),
(30, 'BSc Actuarial Science', 'Commerce', 36, 'Risk, statistics and financial mathematics.', 'Mathematics, English'),
(31, 'BSc Data Science', 'Engineering & IT', 30, 'Machine learning, big data analytics and programming.', 'Mathematics, Physical Science'),
(32, 'BSc Environmental Science', 'Science', 28, 'Ecosystems, climate change and environmental management.', 'Mathematics, Life Sciences, Physical Science'),
(33, 'BSc Biotechnology', 'Science', 30, 'Biological systems, genetics and biomedical research.', 'Mathematics, Physical Science, Life Sciences'),
(34, 'BSc Dietetics', 'Health Sciences', 32, 'Nutrition, food science and dietary planning.', 'Mathematics, Life Sciences, Physical Science'),
(35, 'LLB Law 4 Year', 'Law', 30, 'South African and international law.', 'English, Mathematics');


INSERT INTO University_courses (id, university_id, course_id, faculty_name, min_aps_override) VALUES
-- UCT
(1, 1, 1, 'Faculty of Commerce', NULL),
(2, 1, 2, 'Faculty of Science', NULL),
(3, 1, 3, 'Faculty of Law', NULL),
(4, 1, 4, 'Faculty of Health Sciences', NULL),
(5, 1, 6, 'Faculty of Commerce', NULL),
(6, 1, 7, 'Faculty of Commerce', NULL),
(7, 1, 8, 'Faculty of Commerce', NULL),
(8, 1, 9, 'Faculty of Science', NULL),
(9, 1, 10, 'Faculty of Science', NULL),
(10, 1, 11, 'Faculty of Science', NULL),
(11, 1, 12, 'Faculty of Engineering and the Built Environment', NULL),
(12, 1, 13, 'Faculty of Engineering and the Built Environment', NULL),
(13, 1, 14, 'Faculty of Engineering and the Built Environment', NULL),
(14, 1, 15, 'Faculty of Engineering and the Built Environment', NULL),
(15, 1, 16, 'Faculty of Health Sciences', NULL),
(16, 1, 17, 'Faculty of Health Sciences', NULL),
(17, 1, 18, 'Faculty of Health Sciences', NULL),
(18, 1, 19, 'Faculty of Health Sciences', NULL),
(19, 1, 20, 'Faculty of Humanities', NULL),
(20, 1, 21, 'Faculty of Humanities', NULL),
(21, 1, 22, 'Faculty of Humanities', NULL),
(22, 1, 23, 'Faculty of Humanities', NULL),
(23, 1, 24, 'Faculty of Humanities', NULL),
(24, 1, 25, 'Faculty of Engineering and the Built Environment', NULL),
(25, 1, 26, 'Faculty of Engineering and the Built Environment', NULL),
(26, 1, 27, 'Faculty of Commerce', NULL),
(27, 1, 30, 'Faculty of Commerce', NULL),
(28, 1, 31, 'Faculty of Science', NULL),
(29, 1, 32, 'Faculty of Science', NULL),
(30, 1, 33, 'Faculty of Science', NULL),
(31, 1, 34, 'Faculty of Health Sciences', NULL),
(32, 1, 35, 'Faculty of Law', NULL),
-- UP
(33, 2, 1, 'Faculty of Economic and Management Sciences', NULL),
(34, 2, 2, 'Faculty of Engineering, Built Environment and IT', NULL),
(35, 2, 3, 'Faculty of Law', NULL),
(36, 2, 4, 'Faculty of Health Sciences', NULL),
(37, 2, 5, 'Faculty of Natural and Agricultural Sciences', NULL),
(38, 2, 6, 'Faculty of Economic and Management Sciences', NULL),
(39, 2, 7, 'Faculty of Economic and Management Sciences', NULL),
(40, 2, 8, 'Faculty of Economic and Management Sciences', NULL),
(41, 2, 9, 'Faculty of Natural and Agricultural Sciences', NULL),
(42, 2, 10, 'Faculty of Natural and Agricultural Sciences', NULL),
(43, 2, 11, 'Faculty of Natural and Agricultural Sciences', NULL),
(44, 2, 12, 'Faculty of Engineering, Built Environment and IT', NULL),
(45, 2, 13, 'Faculty of Engineering, Built Environment and IT', NULL),
(46, 2, 14, 'Faculty of Engineering, Built Environment and IT', NULL),
(47, 2, 15, 'Faculty of Engineering, Built Environment and IT', NULL),
(48, 2, 16, 'Faculty of Health Sciences', NULL),
(49, 2, 17, 'Faculty of Health Sciences', NULL),
(50, 2, 18, 'Faculty of Health Sciences', NULL),
(51, 2, 19, 'Faculty of Health Sciences', NULL),
(52, 2, 20, 'Faculty of Humanities', NULL),
(53, 2, 21, 'Faculty of Humanities', NULL),
(54, 2, 22, 'Faculty of Humanities', NULL),
(55, 2, 23, 'Faculty of Humanities', NULL),
(56, 2, 24, 'Faculty of Education', NULL),
(57, 2, 25, 'Faculty of Engineering, Built Environment and IT', NULL),
(58, 2, 26, 'Faculty of Engineering, Built Environment and IT', NULL),
(59, 2, 27, 'Faculty of Economic and Management Sciences', NULL),
(60, 2, 28, 'Faculty of Economic and Management Sciences', NULL),
(61, 2, 29, 'Faculty of Economic and Management Sciences', NULL),
(62, 2, 30, 'Faculty of Economic and Management Sciences', NULL),
(63, 2, 31, 'Faculty of Engineering, Built Environment and IT', NULL),
(64, 2, 32, 'Faculty of Natural and Agricultural Sciences', NULL),
(65, 2, 33, 'Faculty of Natural and Agricultural Sciences', NULL),
(66, 2, 34, 'Faculty of Health Sciences', NULL),
(67, 2, 35, 'Faculty of Law', NULL),
-- WITS
(68, 3, 1, 'Faculty of Commerce, Law and Management', NULL),
(69, 3, 2, 'Faculty of Science', NULL),
(70, 3, 3, 'Faculty of Law', 34),
(71, 3, 4, 'Faculty of Health Sciences', NULL),
(72, 3, 6, 'Faculty of Commerce, Law and Management', NULL),
(73, 3, 7, 'Faculty of Commerce, Law and Management', NULL),
(74, 3, 8, 'Faculty of Commerce, Law and Management', NULL),
(75, 3, 9, 'Faculty of Science', NULL),
(76, 3, 10, 'Faculty of Science', NULL),
(77, 3, 11, 'Faculty of Science', NULL),
(78, 3, 12, 'Faculty of Engineering and the Built Environment', NULL),
(79, 3, 13, 'Faculty of Engineering and the Built Environment', NULL),
(80, 3, 14, 'Faculty of Engineering and the Built Environment', NULL),
(81, 3, 15, 'Faculty of Engineering and the Built Environment', NULL),
(82, 3, 16, 'Faculty of Health Sciences', NULL),
(83, 3, 17, 'Faculty of Health Sciences', NULL),
(84, 3, 19, 'Faculty of Health Sciences', NULL),
(85, 3, 20, 'Faculty of Humanities', NULL),
(86, 3, 21, 'Faculty of Humanities', NULL),
(87, 3, 22, 'Faculty of Humanities', NULL),
(88, 3, 23, 'Faculty of Humanities', NULL),
(89, 3, 25, 'Faculty of Engineering and the Built Environment', NULL),
(90, 3, 26, 'Faculty of Engineering and the Built Environment', NULL),
(91, 3, 27, 'Faculty of Commerce, Law and Management', NULL),
(92, 3, 30, 'Faculty of Commerce, Law and Management', NULL),
(93, 3, 31, 'Faculty of Engineering and the Built Environment', NULL),
(94, 3, 32, 'Faculty of Science', NULL),
(95, 3, 33, 'Faculty of Science', NULL),
(96, 3, 35, 'Faculty of Law', NULL),
-- SU
(97, 4, 1, 'Faculty of Economic and Management Sciences', NULL),
(98, 4, 2, 'Faculty of Science', NULL),
(99, 4, 3, 'Faculty of Law', NULL),
(100, 4, 4, 'Faculty of Medicine and Health Sciences', NULL),
(101, 4, 5, 'Faculty of AgriSciences', NULL),
(102, 4, 6, 'Faculty of Economic and Management Sciences', NULL),
(103, 4, 7, 'Faculty of Economic and Management Sciences', NULL),
(104, 4, 9, 'Faculty of Science', NULL),
(105, 4, 10, 'Faculty of Science', NULL),
(106, 4, 11, 'Faculty of Science', NULL),
(107, 4, 12, 'Faculty of Engineering', NULL),
(108, 4, 13, 'Faculty of Engineering', NULL),
(109, 4, 14, 'Faculty of Engineering', NULL),
(110, 4, 15, 'Faculty of Engineering', NULL),
(111, 4, 16, 'Faculty of Medicine and Health Sciences', NULL),
(112, 4, 17, 'Faculty of Medicine and Health Sciences', NULL),
(113, 4, 18, 'Faculty of Medicine and Health Sciences', NULL),
(114, 4, 19, 'Faculty of Medicine and Health Sciences', NULL),
(115, 4, 20, 'Faculty of Arts and Social Sciences', NULL),
(116, 4, 21, 'Faculty of Arts and Social Sciences', NULL),
(117, 4, 22, 'Faculty of Arts and Social Sciences', NULL),
(118, 4, 24, 'Faculty of Education', NULL),
(119, 4, 25, 'Faculty of Engineering', NULL),
(120, 4, 26, 'Faculty of Engineering', NULL),
(121, 4, 27, 'Faculty of Economic and Management Sciences', NULL),
(122, 4, 30, 'Faculty of Economic and Management Sciences', NULL),
(123, 4, 32, 'Faculty of Science', NULL),
(124, 4, 33, 'Faculty of AgriSciences', NULL),
(125, 4, 34, 'Faculty of Medicine and Health Sciences', NULL),
(126, 4, 35, 'Faculty of Law', NULL),
-- UKZN
(127, 5, 1, 'College of Law and Management Studies', NULL),
(128, 5, 2, 'College of Agriculture, Engineering and Science', NULL),
(129, 5, 3, 'College of Law and Management Studies', NULL),
(130, 5, 4, 'College of Health Sciences', 36),
(131, 5, 5, 'College of Agriculture, Engineering and Science', NULL),
(132, 5, 6, 'College of Law and Management Studies', NULL),
(133, 5, 7, 'College of Law and Management Studies', NULL),
(134, 5, 8, 'College of Law and Management Studies', NULL),
(135, 5, 9, 'College of Agriculture, Engineering and Science', NULL),
(136, 5, 10, 'College of Agriculture, Engineering and Science', NULL),
(137, 5, 11, 'College of Agriculture, Engineering and Science', NULL),
(138, 5, 12, 'College of Agriculture, Engineering and Science', NULL),
(139, 5, 13, 'College of Agriculture, Engineering and Science', NULL),
(140, 5, 14, 'College of Agriculture, Engineering and Science', NULL),
(141, 5, 16, 'College of Health Sciences', NULL),
(142, 5, 17, 'College of Health Sciences', NULL),
(143, 5, 18, 'College of Health Sciences', NULL),
(144, 5, 19, 'College of Health Sciences', NULL),
(145, 5, 20, 'College of Humanities', NULL),
(146, 5, 21, 'College of Humanities', NULL),
(147, 5, 22, 'College of Humanities', NULL),
(148, 5, 23, 'College of Humanities', NULL),
(149, 5, 24, 'College of Education', NULL),
(150, 5, 27, 'College of Law and Management Studies', NULL),
(151, 5, 28, 'College of Law and Management Studies', NULL),
(152, 5, 29, 'College of Law and Management Studies', NULL),
(153, 5, 32, 'College of Agriculture, Engineering and Science', NULL),
(154, 5, 33, 'College of Agriculture, Engineering and Science', NULL),
(155, 5, 34, 'College of Health Sciences', NULL),
(156, 5, 35, 'College of Law and Management Studies', NULL);